my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('simple_site.urls')),
]

simple_site/urls.py
from django.urls import path
from . import views


app_name = 'simple_site'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('delete_comment/<int:comment_id>', views.delete_comment,
         name='delete_comment'),
    path('edit_topic/<int:topic_id>', views.edit_topic, name='edit_topic'),
    path('edit_comment/<int:comment_id>', views.edit_comment,
         name='edit_comment'),
    path('converter/', views.converter, name='converter'),
]

users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.register, name='register'),
]

simple_site/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    '''Topic model'''
    topic = models.CharField(max_length = 200)
    date = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        '''Returns a string representation'''
        return self.topic


class Comments(models.Model):
    '''User's comment'''
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        '''Returns a string representation'''
        return self.comment


class UploadFile(models.Model):
    '''Save file in DB'''
    upload_file = models.FileField(upload_to='uploads/')
    upload_time = models.DateTimeField(auto_now_add=True)

users/models.py
from django.db import models

simple_site/forms.py
from django import forms
from .models import Topic, Comments, UploadFile


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['topic']
        labels = {'topic': ''}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment']
        labels = {'comment': 'New comment:'}
        widgets = {'comment': forms.Textarea(attrs={'cols': 42, 'rows': 5})}


class UploaFileForm(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ['upload_file']

simple_site/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse

from .models import Topic, Comments, UploadFile
from .forms import TopicForm, CommentForm, UploaFileForm

from reportlab.pdfgen import canvas
from io import BytesIO


def home_page(request):
    '''Directs to the home page'''
    return render(request, 'simple_site/home_page.html')


def topics(request):
    '''Directs to the topics page'''
    topics = Topic.objects.all()
    context = {'topics': topics}
    return render(request, 'simple_site/topics.html', context)


@login_required
def topic(request, topic_id):
    '''Directs to the topic page and shows a list of comments on the topic'''
    topic = Topic.objects.get(id=topic_id)
    comments = topic.comments_set.order_by('-date')
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.topic = topic
            new_comment.owner = request.user
            new_comment.save()
            return redirect('simple_site:topic', topic_id=topic.id)
    context = {'form': form, 'topic': topic, 'comments': comments}
    return render(request, 'simple_site/topic.html', context)


@login_required
def new_topic(request):
    '''Page for creating a new theme'''
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            topic_new = form.save(commit=False)
            topic_new.owner = request.user
            topic_new.save()
            return redirect('simple_site:topics')
    context = {'form': form}
    return render(request, 'simple_site/new_topic.html', context)


@login_required
def delete_comment(request, comment_id):
    '''Comment deletion function'''
    comment = Comments.objects.get(id=comment_id)
    topic_id = comment.topic.id
    comment.delete()
    return redirect('simple_site:topic', topic_id)


@login_required
def comment_owner_checker(request, comment_id):
    '''Checks whether the user from the request matches the comment creator'''
    comment = Comments.objects.get(id=comment_id)
    if comment.owner != request.user:
        raise Http404
    else:
        return (request, comment_id)


@login_required
def topic_owner_checker(request, topic_id):
    '''Checks whether the user from the request matches the topic creator'''
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    else:
        return (request, topic_id)


@login_required
def edit_topic(request, topic_id):
    '''Directs to the topic changes page'''
    topic = Topic.objects.get(id=topic_id)
    topic_owner_checker(request, topic_id)
    if request.method != 'POST':
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('simple_site:topics')
    context = {'form': form, 'topic': topic}
    return render(request, 'simple_site/edit_topic.html', context)


@login_required
def edit_comment(request, comment_id):
    '''Directs to the comment changes page'''
    comment = Comments.objects.get(id=comment_id)
    topic = comment.topic
    comment_owner_checker(request, comment_id)
    if request.method == "POST":
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('simple_site:topic', topic_id=topic.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form, 'comment': comment}
    return render(request, 'simple_site/edit_comment.html', context)


def converter(request):
    '''Converting .txt to .pdf'''
    if request.method == 'POST':
        form = UploaFileForm(request.POST, request.FILES)
        if form.is_valid():
            txt_file = request.FILES['upload_file']
            txt_file_content = txt_file.read().decode('utf-8').split('\n')

            buffer = BytesIO()
            pdf = canvas.Canvas(buffer)
            x = 60
            y = 780
            length = 90
            pdf.setFont("Helvetica", 10)

            # with open(txt_file.name, 'r') as f:
            #     txt_file_content = f.readlines()

            for string_inside in txt_file_content:
                index = 0
                if len(string_inside) >= length:
                    strings_in_string_inside = round(len(string_inside) /
                                                         length)
                    for string in range(int(strings_in_string_inside)):
                        string_to_print = string_inside[index:index + length]
                        pdf.drawString(x, y, string_to_print.rstrip('\n'))
                        index += length
                        y -= 13
                elif len(string_inside) < length:
                    pdf.drawString(x, y, string_inside[:-1])
                    y -= 13
            pdf.save()

            buffer.seek(0)

            response = HttpResponse(buffer, content_type='application/pdf')
            response['Content-Disposition'] = 'attachment; ' \
                                              'filename="output.pdf"'
            return response
    else:
        form = UploaFileForm()
    context = {'form': form}
    return render(request, 'simple_site/home_page.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('simple_site:home_page')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

simple_site/templates/simple_site/base.html
<a href="{% url 'simple_site:home_page' %}">Home page</a>
<br><a href="{% url 'simple_site:topics' %}">Topics</a></br>
{% if user.is_authenticated %}
  Hello, {{ user.username }}
  <br><a href="{% url 'users:logout' %}">Logout</a></br>
{% else %}
  <a href="{% url 'users:register' %}">Register</a>
  <br><a href="{% url 'users:login' %}">Login</a></br>
{% endif %}
<br></br>

{% block content %}{% endblock content  %}

simple_site/templates/simple_site/edit_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>EDIT COMMENT</title>
</head>
<body>
{% extends 'simple_site/base.html' %}
{% block content %}

  <h2>Edit your comment here:</h2>

  <form method="post" action="{% url 'simple_site:edit_comment' comment_id=comment.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">save changes</button>
  </form>

{% endblock content %}
</body>
</html>

simple_site/templates/simple_site/edit_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>EDIT TOPIC</title>
</head>
<body>
{% extends 'simple_site/base.html' %}
{% block content %}

  <h2>Edit topic: {{ topic }}</h2>

  <form method="post" action="{% url 'simple_site:edit_topic' topic_id=topic.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>

{% endblock content %}
</body>
</html>

simple_site/templates/simple_site/home_page.html
<!DOCTYPE html>
<html>
  <head>
    <charset = "UTF-8">
    <title>HOME PAGE</title>
  </head>
  <body>
  {% extends 'simple_site/base.html' %}

  {% block content %}

    <h2>
      On this site you can write topics and told about it with another users.
    </h2>

    <h3>
      <a href="{% url 'simple_site:topics' %}">Here</a> we can talking on any
      themes
    </h3>

    <h2>
    Or use convertor .txt to .pdf below:
    </h2>

    <form action="{% url 'simple_site:converter' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="file" name="upload_file">
      <button type="submit">Convert to PDF</button>
    </form>

  {% endblock content %}
  </body>
</html>

simple_site/templates/simple_site/new_topic.html
{% extends 'simple_site/base.html' %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'>
    <title>NEW TOPIC</title>
  </head>
  <body>
    {% block content %}
      
      <p>Add topic:</p>      

      <form action="{% url 'simple_site:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>save topic</button>
      </form>

    {% endblock content  %}
  </body>
</html>

simple_site/templates/simple_site/topic.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset 'UTF-8'>
    <title>TOPIC</title>
  </head>
  <body>

    {% extends 'simple_site/base.html' %}
    
    {% block content %}

      <h1>{{ topic }}</h1>

      <form action="{% url 'simple_site:topic' topic_id=topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>save comment</button>
      </form>

      <p>
      {% for comment in comments %}
        {% if comment.owner == request.user %}
          <p>================================</p>
          {{ comment.comment|linebreaks }}
          <p>================================</p>
          {{ comment.owner }}
          {{ comment.date|date:'H:i, M d' }}
          <a href="{% url 'simple_site:delete_comment' comment.id %}">delete comment</a>
          <a href="{% url 'simple_site:edit_comment' comment.id %}">edit comment</a>
          <p>--------------------------------</p>
        {% else %}
          <p>================================</p>
          {{ comment.comment|linebreaks }}
          <p>================================</p>
          {{ comment.owner }}
          {{ comment.date|date:'H:i, M d' }}
          <p>--------------------------------</p>
        {% endif %}
      {% empty %}
        No comments yet.
      {% endfor %}
      </p>

    {% endblock content %}
  </body
</html>

simple_site/templates/simple_site/topics.html
<!DOCTYPE html>
<html>
  <head>
    <charset = 'UTF-8'>
    <title>TOPICS</title>
  </head>
  <body>
    {% extends 'simple_site/base.html' %}
    
    {% block content %}

      <h1>Topics:</h1>
      
      {% for topic in topics %}
        {% if topic.owner == request.user %}
          <ul/>
            <a href="{% url 'simple_site:topic' topic.id %}">{{ topic }}</a>
            <a href="{% url 'simple_site:edit_topic' topic.id %}">edit topic</a>
          </ul>
        {% else %}
          <ul>
            <a href="{% url 'simple_site:topic' topic.id %}">{{ topic }}</a>
          </ul>
        {% endif %}
      {% empty %}
        No topic here.
      {% endfor %}

     <br><a href="{% url 'simple_site:new_topic' %}">Write new topic</a></br>

    {% endblock content %}
  </body>
</html>